name: Auto Fetch Jobs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install beautifulsoup4 requests
      - run: python fetch_jobs.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add jobs/
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto update job listings"
          git push
