name: Fetch Jobs and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install beautifulsoup4 requests python-dateutil

    - name: Run job scraper
      run: python fetch_jobs.py

    - name: Show scraped jobs
      run: ls -la jobs/

    - name: Commit scraped jobs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add jobs/*.json
        git commit -m "🗂️ Auto-update scraped job data" || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
