name: Fetch Jobs and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *' # 5:00 AM IST
  push:
    paths:
      - fetch_jobs.py
      - requirements.txt
      - .github/workflows/fetch.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', 3.11, 3.12]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env

    - name: Run fetch_jobs.py
      run: python fetch_jobs.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add jobs/ job_manifest.json || true
        if ! git diff --cached --quiet; then
          git commit -m "[bot] Update jobs data $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit."
        fi

        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install torch transformers
        if [ -f tests/test_basic.py ]; then pytest tests/; else echo "No tests yet"; fi

    - name: Commit scraped jobs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add jobs/*.json
        git commit -m "🗂️ Auto-update scraped job data" || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
