name: Auto Fetch Jobs

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write # Needed for pushing changes

jobs:
  fetch_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch jobs data
        run: |
          python fetch_jobs.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto update: fetched jobs data"
          git push origin HEAD
